package suite

import (
	ssov1 "SSO/contract/gen/go/sso"
	"SSO/internal/config"
	"context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"net"
	"strconv"
	"testing"
)

const (
	HOST = "localhost"
)

type Suite struct {
	*testing.T
	Cfg        *config.Config
	AuthClient ssov1.AuthClient
}

func New(t *testing.T) (context.Context, *Suite) {
	t.Helper()
	t.Parallel()

	// Can be switched into auto-testing in gh-action
	// just get config_path using env (os.Getenv)
	cfg := config.LoadByPath("../config/local_tests.yaml")

	// creating a context with timeout from config
	ctx, cancelCtx := context.WithTimeout(context.Background(), cfg.GRPC.Timeout)

	// clean after testing when test ended
	t.Cleanup(func() {
		t.Helper()
		cancelCtx()
	})

	cc, err := grpc.DialContext(context.Background(),
		grpcAddress(cfg),
		grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatalf("can't failed to server %v", err)
	}

	// auto-generated by gRPC client
	return ctx, &Suite{
		T:          t,
		Cfg:        cfg,
		AuthClient: ssov1.NewAuthClient(cc),
	}
}

func grpcAddress(cfg *config.Config) string {
	return net.JoinHostPort(HOST, strconv.Itoa(cfg.GRPC.Port))
}
