name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start_server_and_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: make migration
        run: make migrate

      - name: make TestsMigration
        run: make migrateTest

      - name: start server in background
        run: make auth &

      - name: make tests
        run: make tests

      - name: Stop server
        run: kill $(pgrep -f "main.go")